### PR TITLE
Add No Slot Clock support

### PR DESCRIPTION
**Pull request by code-bythepound**
Add No Slot Clock support using nsc.ts from Apple2JS repo.  That file is covered by MIT license, see it for details.
NSC effectively sits in C300 space to be compatible with drivers from Reactive Micro and with A2OSX.  Tested and seems to be working with both.  Writing to the device to set the time is not supported.

Chris - I wasn't sure if I should implement this inside checkSlotIO, since its result is written to the ROM space, and that seemed wrong in this case since the result is temporary.  Please take a look.

### CODE REVIEW

**Comment by code-bythepound** [comment]
For the clock to show up with the built-in Prodos 2.4.2 disk, we would need to add the NSC driver to it.

**Comment by code-bythepound** [comment]
Also upgraded Prodos to 2.4.3 and added NSC driver to it.

**Comment by ct6502** [comment]
I did some tweaks to the code, simplifying it and also removing the check in "memSet" since the no slot clock only responds to reads, not writes.

**Comment by code-bythepound** [comment]
Great, thanks.

**Pull request merged**
