### PR TITLE
Ultima 5 Multi-instrument MIDI mods (for review only)

### PR DESCRIPTION
**Pull request by code-bythepound**
This is a modification based on the work of "Cloudschatze" in his article and presentation here: https://forum.vcfed.org/index.php?threads/how-you-could-have-been-playing-ultima-v-in-1988.61980/.  His change allows a Roland U-110 MIDI module to receive the stock MIDI sequence from U5 and remasters that uni-channel MIDI sequence into a multi-channel (ie: multi-instrument) sequence on-device.  My change takes his mappings and ranges and converts them in real time to General MIDI instruments and tunings providing a similar experience.

TO TEST: launch U5.  Go to Activate Music -> Change Music Configuration, add Passport to slot 2, and hit enter.  In the Midi Information screen, select Channel 1 (default), 16 voices, and then enter the numbers 1-15 for "Midi Number" in each song (where Ultima Theme is '1' and Rule Britannia is '15').  Then hit enter on each song to play.

Still TODO:
* Cleanup of code and debug prints
* Add ability to detect U5 and turn on this change only in that game (the mods are always on in the current change).  I tried but failed to do this as U5 seems to reload large sections of code during gameplay and setup from disk.
* Possibly tune the instruments, but this is of lower priority.
* Possibly add more of the U-110's MIDI controller type support, but not all MIDI devices will support this.

I have had the best luck testing with https://signal.vercel.app/ for WebMIDI.

### CODE REVIEW

**Comment by ct6502** [comment]
This looks awesome. I haven't had a chance to try it yet, but in the meantime, you can detect Ultima V by looking at memory address  0x202. It contains the data [0x55, 0x4C, 0x54, 0x49, 0x4D, 0x41, 0x35], which spells out "ULTIMA5". I don't know if this was true in the original game as well, or is just because of the ProDOS port, but that string seems to stay there for the entire game.

**Comment by code-bythepound** [comment]
Great, that worked.  I'll get this finished up.

**Comment by code-bythepound** [comment]
Ok, should be ready for review.  Thanks.

**Comment by ct6502** [comment]
This looks really good - just one comment - the "midiinterface.ts" is getting pretty long. Should we move all the Ultima V stuff (including setEnhancedMidi) into a new file?

**Review by ct6502 — APPROVED** [review]
This looks really good - just one comment - the "midiinterface.ts" is getting pretty long. Should we move all the Ultima V stuff (including setEnhancedMidi) into a new file? I'll go ahead and approve the merge, and then maybe we can tweak it in the future.

**Pull request merged**
